create table "public"."project" (
    "id" bigint generated by default as identity not null,
    "title" text default 'Untitled Project'::text,
    "creator_id" uuid default auth.uid(),
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."project" enable row level security;

CREATE UNIQUE INDEX project_pkey ON public.project USING btree (id);

alter table "public"."project" add constraint "project_pkey" PRIMARY KEY using index "project_pkey";

create policy "Enable insert for authenticated users only and matching user_id"
on "public"."project"
as permissive
for select
to authenticated
using ((auth.uid() = creator_id));



